version: "3"
services:
  node:
    build:
      context: .
    tty: true
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/Users/tshira/docker_react
    command: sh -c "cd sample-project && yarn start"
    ports:
      - "3000:3000"
